language: ruby
cache: bundler
rvm:
- 2.4.1
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rspec
before_install:
- gem update --system
- gem install bundler:2.0.2
deploy:
  provider: heroku
  api_key:
    secure: LBh3tkMaeWenM123T1AaGDnoflLB6XkX+AHVH855ssJ5Dhr/eKa0yATl+kCJjy6WhGJq3oTgWpeq8mUeA3SSAgNfGkLM3J4/qhOrqe4cNmhFPBNX/nY118HgObwzn0jr3w4VrFsLf5ytJ05qo50h5rrEfPjrM5/44OzqLn1sCtJW5xRUBdhMugAFRN1oiX121feJUlUTMzFbM3gNJy6EG5VRAuTPr9ROYyC7+bZMCXid1W8+j1ZKLosaCvQbC+swnNzQV+RMpJqrOQcABqVRWljc5f1/wSdsta/9mWvSCUkAVl1ck0giMoNVcN9xPNbT4KZ3L7o/3fPwnkIVVspviTfFDo1mDSUPYpBZD8h2Su601PbswOG+uvzFETUsebiuRt56Ta9JolQdBSHMlDNFzz+XRbSmkpitSGUXSJ2+8WyFAfT9Ds4UcoX+tqrXe7A5mKdskAWA4kIm1cXZWFtamzYCIL631PLry4LhY3VMWi0jSUJLRZbm7bZAudeZ4nLZMwHLzowAVTzSCmno0068u2P68t+DA2dvlqlN/JffhhYgkiU+aXpC0WPbxG8ycKkDC8AMLrUQOT6ole9bTmrxLObZkVP5PY2e1JBR4VNy6KQso55lcYDl000UNOEzwqf9fDrNXbKquBQu+CbWkKsiVNZ/8I2WoBh15uieWwuDMKU=
  app_name: weatherforsweaters
